### PR TITLE
chore(sample): add cards actions sample

### PR DESCRIPTION
**Pull request by vulvulune**

### CODE REVIEW

**Comment by vulvulune** [comment]
Fix the issue #467

**Comment by Thanood** [comment]
Sorry for not responding so long. A lot of real life happened..
I've tried the sample but the actions on the last card should only be visible when the card is revealed, right?

I will have a look but maybe you already know a solution. 😃 
Also, in #467 you mentioned you'd like to update the gist so I'm wondering if this PR links to the most recent gist.

**Comment by vulvulune** [comment]
Hello,

I updated the gist this morning, and find a bug corrected in the PR #476.

When you will do a new release, my gist will work.

**Comment by Thanood** [comment]
I'll try it.
Not sure if I can do a release today, I'm coming home late.
But I will create one tomorrow the latest.

Would be nice to fix that AMD issue (#473) before that but I guess I'll need to go on without it for now.

**Comment by Thanood** [comment]
I think I got the text in the card wrong.
It says:

> This card has reveal true and the actions are visible only when the card is revealed.

But actually, if the actions are not made sticky, the reveal will appear above the card actions.
(btw. I don't think my sentence above makes that any clearer 😂 )

**Comment by vulvulune** [comment]
You are right, the text on the last card was wrong. I updated the gist.

**Comment by vulvulune** [comment]
Thank you for the new release, Can you please provide this file: "https://rawgit.com/aurelia-ui-toolkits/aurelia-materialize-bundles/0.31.0/config2.js"

I already update my gist to use it.

**Comment by Thanood** [comment]
Done! 👍

**Pull request merged**
