### PR TITLE
refactor(md-dropdown): remove legacy fix

### PR DESCRIPTION
**Pull request by vulvulune**
Same as PR #461 and #462 but with correct convention and correct files.

As discussed in the issue #458 I've removed the legacy dropdown-fix. It was for an old version of materialize and not used by default.

Breaking changes:
- The method useDropdownFix doesn't exist anymore.

### CODE REVIEW

**Comment by Thanood** [comment]
I wonder if we should issue a warning if someone still uses `.useDropdownFix()`. Maybe just a simple `console.warn` in `config-builder.js`.

**Comment by vulvulune** [comment]
Ok I add a warning

**Comment by vulvulune** [comment]
What do you think of:
`console.warn("The method useDropdownFix has no effect in this version and will be removed in a future version.");`

**Comment by Thanood** [comment]
I like that. 😃

**Pull request merged**
