### PR TITLE
Add stopPropagation option on dropdown 

### PR DESCRIPTION
**Pull request by vulvulune**
Fix the issue #451

### CODE REVIEW

**Comment by vulvulune** [comment]
This PR add this option only to the custom attribute on not on the element.

**Comment by vulvulune** [comment]
I updated the PR, now it add the option to the attribute and to the element.

**Comment by Thanood** [comment]
Thanks a lot! 👍 
The element is a placeholder, btw. I've tried that in the beginning and went with the attribute instead. Maybe we should remove that.

One thing: could you use a commit message which corresponds to our [commit message convention](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/wiki/Development-Protocol)? The format is readable by `conventional-changelog` and will be used to generate release notes.

For this case it would be: `feat(md-dropdown): add stopPropagation option`.
No need to change the commits now, I can adapt the changelog manually. Just for next time maybe. 😃

**Comment by vulvulune** [comment]
I will open again a pull request with a single commit and clean message. Don't spend your time to correct this one.

**Pull request closed without merging**
