### PR TITLE
docs(install): change bridge bundle resources

### PR DESCRIPTION
**Pull request by Ullfis**
Version 0.17.1 added style for chip and range :+1:

### CODE REVIEW

**Comment by Thanood** [comment]
You're right, thanks! :smiley: 
I've had the feeling that I forgot something important..

I wonder if we can change this somehow so that users don't need to add this. Maybe add these to build resources. At least, that works for webpack.

**Comment by Ullfis** [comment]
I just tried to change the bridge bundle resources in [this project](https://github.com/Ullfis/au-cli-skel) and it worked!

```json

      {
        "name": "materialize-bundle.js",
        "dependencies": [
          "jquery",
          {
            "name": "materialize-css",
            "path": "../node_modules/materialize-css/dist",
            "main": "js/materialize.amd",
            "deps": [
              "jquery"
            ]
          },
          {
            "name": "aurelia-materialize-bridge",
            "path": "../node_modules/aurelia-materialize-bridge/dist/amd",
            "main": "index",
            "deps": [
              "jquery"
            ],
            "resources": [
              "**/*.{css,html}"
            ]
          }
        ]
      }, 

```

aurelia-cli@0.20.1

**Comment by Thanood** [comment]
:tada:

**Comment by Ullfis** [comment]
Confirming that it works in 2 other aurelia-cli projects.

**Comment by Thanood** [comment]
That did not always work, right?
I hope it stays as it is now. ;-)

**Comment by Ullfis** [comment]
It didn't work at all earlier :)

Trying to amend doc changes

**Comment by Thanood** [comment]
Thanks!

I'd like to put these docs into a GitBook so that we don't have to update (build, bundle, upload) the app everytime the docs change.

**Comment by Thanood** [comment]
```
Unhandled rejection Error: src/../scripts/materialize-bundle.html HTTP status: 404
```

I wonder why it's trying to load that..

**Comment by Ullfis** [comment]
Strange. I have not had that error. Latest cli version? Dropped node_modules and reinstalled? Do [this project](https://github.com/Ullfis/au-cli-skel) run?

**Comment by Thanood** [comment]
I will try deleting node_modules and reinstall. Did not yet try running your project but copied the `aurelia.json`.

**Comment by Thanood** [comment]
Your project runs perfectly. 👍 
Hmm, I guess I need to compare now.

**Comment by Thanood** [comment]
The first difference seems to be windows path seperators and you're using typescript. 😃 
Interesting...

**Comment by Thanood** [comment]
Seems to be some kind of fallback request when anything is not found in the bundle.
I removed the wildcards and put everything back in, then added chips and range css and it worked.. Very strange.

Now, my global aurelia-cli is different from my local one. I'll try upgrading both now.

**Comment by Thanood** [comment]
I've noticed the trace stopping at:
```
Tracing aurelia-materialize-bridge/collection/collection-item...
```

With your project it traces all exports.

**Comment by Ullfis** [comment]
Very strange. I cant think why it should be different. I will try an esnext cli project later.

**Comment by Thanood** [comment]
I'll try and generate a new project after upgrading everything.

**Comment by Thanood** [comment]
Okay, I'm giving up for today..
Does [this project](https://github.com/Thanood/md-contact-manager) run for you?

I must be overlooking something..

**Comment by Thanood** [comment]
https://github.com/aurelia/webpack-plugin/issues/11

> Also, only typescript type (option 2) with the command "au new" works. First default option does not.

I don't know if that's true but if it is, that may be a reason (and everybody else in the world would create TS projects 😂 ).

**Comment by Ullfis** [comment]
#### esnext

```bash
...
Tracing aurelia-materialize-bridge/click-counter...
Tracing aurelia-materialize-bridge/breadcrumbs/breadcrumbs...
Tracing aurelia-materialize-bridge/breadcrumbs/breadcrumbs...
Tracing aurelia-materialize-bridge/card/card...
Tracing aurelia-materialize-bridge/card/card...
Tracing aurelia-materialize-bridge/carousel/carousel...
Tracing aurelia-materialize-bridge/carousel/carousel-item...
Tracing aurelia-materialize-bridge...
Tracing text...
...
```
and so on. It compiled and I could start browser but missed components, so page wouldn't load.

I had to add all resources before it worked. One interesting thing.. I forgot to set stub to false (after adding all components) and it worked anyway. I did not add aurelia-validation on this test.

**Comment by Thanood** [comment]
I've noticed that, too as you know..
This also happened with a TypeScript project. So, validation..?

@JeroenVinke mentioned [an issue](https://github.com/aurelia/cli/issues/270#issuecomment-240940254) where he found out that matching all resources timed out. That would fit the "randomness" of this problem.

**Comment by JeroenVinke** [comment]
I have created https://github.com/aurelia/cli/issues/368

**Comment by Ullfis** [comment]
I changed build script on the [typescript project](https://github.com/Ullfis/au-cli-skel) so it clean the output folder and copy scripts during first build. After that I had to add back bridge resources to make the project run.

Build time related?

**Comment by Thanood** [comment]
It works for me with the changes from Jeroen's PR here:
https://github.com/aurelia/cli/pull/369

**Comment by Ullfis** [comment]
Works for me 2. Both typescript and esnext cli project.

**Comment by Thanood** [comment]
Great!
I will wait for the PR being merged. In the meantime I moved the installation instructions to GitBook docs:
https://www.gitbook.com/read/book/aurelia-ui-toolkits/materialize-bridge-docs

These instructions include chip and range.
Will update the app when I come home in a few hours.

**Comment by Thanood** [comment]
0.21.0 is out with the fix 🎉

**Comment by DarienFord** [comment]
So strange; Looks like I'm having this same issue in 0.24.0

**Comment by DarienFord** [comment]
So strange; I'm having the same 
`Unhandled rejection Error: src/../scripts/materialize-bundle.html HTTP status: 404` but in 0.24.0

**Comment by Thanood** [comment]
@DarienFord This is usually a follow-up error, I've seen it frequently when files are missing from the bundle. There should be another error message with the "real" error. Could you check that and post the error if I'm right? 😃

**Pull request merged**
