### PR TITLE
Aurelia validation

### PR DESCRIPTION
**Pull request by Ullfis**

### CODE REVIEW

**Comment by Thanood** [comment]
Looks great, checking it out now.
Do you think we need an "error" color? I saw your static color in `md-colors`. I'll have a look what we can do about that.

**Comment by Ullfis** [comment]
Error color sounds great :smile: Maybe also consider a success color.

**Comment by Thanood** [comment]
I'll add another issue for that.

Do you know if it's possible to have default values for html-only components (like `md-colors`)?
I'd like to not break existing code (by requiring two additional attributes) but still like to keep the simple html-only thing that it is today.

If it's not possible I simply add a js file.

**Comment by Ullfis** [comment]
I am not sure. Maybe a js file is the way to go here.

**Pull request merged**
