### PR TITLE
Added md-readonly attribute to md-input, md-radio, md-checkbox and md-switch.

### PR DESCRIPTION
**Pull request by HIRANO-Satoshi**
Hi,

I added md-readonly attribute to md-input, md-radio, md-checkbox and md-switch, since I needed readonly only input fields to show values.

If you merge this PR, please write about it in your document.

I think it would be much better if we could have a very versatile option such as md-option to give any kind of attribute.

I also fixed a typo in switch.html from *<input .... >*  to *<input .../>*.

### CODE REVIEW

**Comment by Thanood** [comment]
Hi @HIRANO-Satoshi,

thanks for the contribution and feedback. 😃 
I see you removed a test (or trial) with that `mdOption` attribute. How did that work out? It's an interesting idea.

Anyway, would you mind changing two things so I can merge you PR?
- please remove the `dist` folder from the commit to have a clean setup
- please change commit messages to adhere to out commit message [conventions](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/wiki/Development-Protocol) for easier changelog generation - f.i.: `feat(md-input): add md-readonly`

As for the last point: it's enough to do that with another commit when removing the `dist` folder, not necessary to change existing commit messages.

Thanks! 👍

**Comment by HIRANO-Satoshi** [comment]
Sorry. I will change and submit again.

The master has the dist and generated files. Should I delete them and commit?


I wanted to do the following. But I think ${mdOption} did not work. Is there a way to add the attributes?

```
// usage.html
<md-tag md-option="attribute1 attribute2"
```

```
// md-tag.js
@bindable() mdOption = "";
```

```
// md-tag.html
<tag ${mdOption}
```

**Comment by Thanood** [comment]
> Should I delete them and commit?

I think that should do it. 😃 

Regarding `mdOption`:
I think you would need to parse the input and use `element.addAttribute(...)` directly. Or split the parsed options into attributes and bind them. With the former approach you'll also be able to have both single attributes and `mdOption`. But that is just a guess, I didn't actually try it.

**Comment by HIRANO-Satoshi** [comment]
I did. If I need to do more, please tell me.

At this moment I'm satisfied with the readonly. I think it would be better for Aurelia to have "catch all other attributes" or something like that.

**Comment by Thanood** [comment]
Hi, sorry for not merging yet, I will do it today.

**Comment by HIRANO-Satoshi** [comment]
Thanks.

**Pull request merged**
