### PR TITLE
feat(datepicker): add slot support for datepicker

### PR DESCRIPTION
**Pull request by sjclark76**

### CODE REVIEW

**Comment by MaximBalaganskiy** [comment]
What would be a use case for this?

**Comment by sjclark76** [comment]
The use case would be to support Icon Prefixes for datepicker inputs. The md-datepicker component used to be an attribute so it wasn't a problem. In the new version of the bridge it is now an html component and we can no longer support this scenario.

**Comment by sjclark76** [comment]
> What would be a use case for this?

The use case would be to support Icon Prefixes for datepicker inputs. The md-datepicker component used to be an attribute so it wasn't a problem. In the new version of the bridge it is now an html component and we can no longer support this scenario.

**Comment by MaximBalaganskiy** [comment]
Thanks, done.

**Pull request merged**
