### PR TITLE
fix(md-tabs): reset click event in refresh method to allow dynamically added tabs

### PR DESCRIPTION
**Pull request by swalters**
to fire the custom tabSelected event

### CODE REVIEW

**Comment by Thanood** [comment]
Thanks. 👍 

Can you change the commit message to use our [commit message convention](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/wiki/Development-Protocol), please? It's used to generate the changelog. 😃 

Although I could add to the changelog manually this time.

**Comment by swalters** [comment]
That's what I get for hurrying :)  Does editing the PR commit do it or do I need to submit another PR with correct verbiage?

**Comment by Thanood** [comment]
I'm not sure, tbh. Maybe there is a way in Github/git to change it..
~~It's possible before pushing to change the commit message.~~

You did it while I was writing. 😄

**Comment by swalters** [comment]
Yes, it wasn't as painful as I thought

**Comment by Thanood** [comment]
How did you do it?

**Comment by swalters** [comment]
https://help.github.com/articles/changing-a-commit-message/#rewriting-the-most-recent-commit-message

git commit --amend
git push --force

**Comment by Thanood** [comment]
Awesome, thanks! 👍 
I will save the link for later (and I hope I don't forget that I saved it -,-).

**Pull request merged**
