### PR TITLE
Added disabled bindable on md-input custom element

### PR DESCRIPTION
**Pull request by Kukks**
#179

### CODE REVIEW

**Comment by Thanood** [comment]
Please provide a sample in the docs for new features.
(as discussed in chat :smile: )

**Comment by Kukks** [comment]
Done ;)

**Comment by Thanood** [comment]
Thank you! :+1:

**Comment by Thanood** [comment]
Please [see here](https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge/wiki/Development-Protocol) for some conventions we use to help auto-generate the changelogs.

**Comment by Thanood** [comment]
Please also remember to lint your changes. Got these linter errors:
```
sample\src\samples\input\basic-use.js
  8:4  error  Expected indentation of 4 space characters but found 0  indent

sample\src\samples\input\textarea.js
  8:4  error  Expected indentation of 4 space characters but found 0  indent

✖ 2 problems (2 errors, 0 warnings)
```

I propose using an editorconfig](http://editorconfig.org/#download) plugin for your editor of choice. It should automatically apply our formatting conventions set in a `.editorconfig` file.

**Comment by Thanood** [comment]
The PR is uploaded in 0.6.0 and visible in the app catalog.

**Pull request merged**
